PRAGMA foreign_keys = ON;

-- Generated by scripts/geocode-live-journey.mjs from cached Nominatim results.

-- Automated coordinates are intentionally not marked as human verified.

UPDATE administrative_areas SET
  latitude = 35.9754168, longitude = 139.4160114,
  coordinate_source = 'osm-nominatim:relation:1768185',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_11';

UPDATE administrative_areas SET
  latitude = 35.4342935, longitude = 139.374753,
  coordinate_source = 'osm-nominatim:relation:2689487',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_14';

UPDATE administrative_areas SET
  latitude = 35.6768601, longitude = 139.7638947,
  coordinate_source = 'osm-nominatim:relation:1543125',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_13';

UPDATE administrative_areas SET
  latitude = 35.549399, longitude = 140.2647303,
  coordinate_source = 'osm-nominatim:relation:2679957',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_12';

UPDATE administrative_areas SET
  latitude = 34.6198813, longitude = 135.490357,
  coordinate_source = 'osm-nominatim:relation:341906',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_27';

UPDATE administrative_areas SET
  latitude = 34.9991645, longitude = 137.254574,
  coordinate_source = 'osm-nominatim:relation:3560336',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_23';

UPDATE administrative_areas SET
  latitude = 1.2899175, longitude = 103.8519072,
  coordinate_source = 'osm-nominatim:relation:17140517',
  coordinates_verified_at = NULL
WHERE id = 'area_sg';

UPDATE administrative_areas SET
  latitude = 34.914934, longitude = 134.860666,
  coordinate_source = 'osm-nominatim:relation:356912',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_28';

UPDATE administrative_areas SET
  latitude = 38.3880155, longitude = 140.9761025,
  coordinate_source = 'osm-nominatim:relation:3790801',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_04';

UPDATE administrative_areas SET
  latitude = 37.6452283, longitude = 138.7669125,
  coordinate_source = 'osm-nominatim:relation:3559887',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_15';

UPDATE administrative_areas SET
  latitude = 34.2480104, longitude = 134.0586579,
  coordinate_source = 'osm-nominatim:relation:3795064',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_37';

UPDATE administrative_areas SET
  latitude = 25.0375198, longitude = 121.5636796,
  coordinate_source = 'osm-nominatim:relation:1293250',
  coordinates_verified_at = NULL
WHERE id = 'area_tw_taipei';

UPDATE administrative_areas SET
  latitude = 32.6450475, longitude = 130.6341345,
  coordinate_source = 'osm-nominatim:relation:1842185',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_43';

UPDATE administrative_areas SET
  latitude = 13.7524938, longitude = 100.4935089,
  coordinate_source = 'osm-nominatim:relation:92277',
  coordinates_verified_at = NULL
WHERE id = 'area_th_bangkok';

UPDATE administrative_areas SET
  latitude = 31.521587, longitude = 130.5474077,
  coordinate_source = 'osm-nominatim:relation:1842186',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_46';

UPDATE administrative_areas SET
  latitude = 35.9263502, longitude = 136.6068127,
  coordinate_source = 'osm-nominatim:relation:357112',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_18';

UPDATE administrative_areas SET
  latitude = 37.3662591, longitude = 140.2511854,
  coordinate_source = 'osm-nominatim:relation:1800608',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_07';

UPDATE administrative_areas SET
  latitude = 33.8070292, longitude = 135.5930743,
  coordinate_source = 'osm-nominatim:relation:908959',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_30';

UPDATE administrative_areas SET
  latitude = 34.8581334, longitude = 133.7759256,
  coordinate_source = 'osm-nominatim:relation:3794962',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_33';

UPDATE administrative_areas SET
  latitude = 39.6898802, longitude = 140.342608,
  coordinate_source = 'osm-nominatim:relation:3791413',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_05';

UPDATE administrative_areas SET
  latitude = 35.7867449, longitude = 137.0460777,
  coordinate_source = 'osm-nominatim:relation:760746',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_21';

UPDATE administrative_areas SET
  latitude = 33.1819875, longitude = 131.4270217,
  coordinate_source = 'osm-nominatim:relation:356911',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_44';

UPDATE administrative_areas SET
  latitude = 33.6251241, longitude = 130.6180016,
  coordinate_source = 'osm-nominatim:relation:1553735',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_40';

UPDATE administrative_areas SET
  latitude = 33.1154683, longitude = 129.7874339,
  coordinate_source = 'osm-nominatim:relation:1842151',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_42';

UPDATE administrative_areas SET
  latitude = 33.2185408, longitude = 130.1296585,
  coordinate_source = 'osm-nominatim:relation:1842150',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_41';

UPDATE administrative_areas SET
  latitude = 36.6782167, longitude = 139.8096549,
  coordinate_source = 'osm-nominatim:relation:1800742',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_09';

UPDATE administrative_areas SET
  latitude = 43.4519831, longitude = 142.8197834,
  coordinate_source = 'osm-nominatim:relation:3795658',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_01';

UPDATE administrative_areas SET
  latitude = -6.1754049, longitude = 106.827168,
  coordinate_source = 'osm-nominatim:relation:6362934',
  coordinates_verified_at = NULL
WHERE id = 'area_id_jakarta';

UPDATE administrative_areas SET
  latitude = 22.3492155, longitude = 114.1857978,
  coordinate_source = 'osm-nominatim:relation:913110',
  coordinates_verified_at = NULL
WHERE id = 'area_hk';

UPDATE administrative_areas SET
  latitude = 35.242552, longitude = 135.454601,
  coordinate_source = 'osm-nominatim:relation:2137477',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_26';

UPDATE administrative_areas SET
  latitude = 32.097681, longitude = 131.294542,
  coordinate_source = 'osm-nominatim:relation:1842184',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_45';

UPDATE administrative_areas SET
  latitude = 34.9332488, longitude = 138.0955398,
  coordinate_source = 'osm-nominatim:relation:3793581',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_22';

UPDATE administrative_areas SET
  latitude = 36.6468015, longitude = 137.2183531,
  coordinate_source = 'osm-nominatim:relation:3793529',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_16';

UPDATE administrative_areas SET
  latitude = 36.1143945, longitude = 138.0319015,
  coordinate_source = 'osm-nominatim:relation:3560284',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_20';

UPDATE administrative_areas SET
  latitude = 34.2963089, longitude = 135.8816819,
  coordinate_source = 'osm-nominatim:relation:358631',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_29';

UPDATE administrative_areas SET
  latitude = 34.5666725, longitude = 132.753565,
  coordinate_source = 'osm-nominatim:relation:3218753',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_34';

UPDATE administrative_areas SET
  latitude = 40.886943, longitude = 140.590121,
  coordinate_source = 'osm-nominatim:relation:1834655',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_02';

UPDATE administrative_areas SET
  latitude = 34.2379614, longitude = 131.5873845,
  coordinate_source = 'osm-nominatim:relation:4016543',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_35';

UPDATE administrative_areas SET
  latitude = 35.247154, longitude = 136.109385,
  coordinate_source = 'osm-nominatim:relation:357800',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_25';

UPDATE administrative_areas SET
  latitude = 52.0799838, longitude = 4.3113461,
  coordinate_source = 'osm-nominatim:relation:192737',
  coordinates_verified_at = NULL
WHERE id = 'area_nl_hague';

UPDATE administrative_areas SET
  latitude = 33.6569018, longitude = 133.5606241,
  coordinate_source = 'osm-nominatim:relation:3795031',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_39';

UPDATE administrative_areas SET
  latitude = 37.5666791, longitude = 126.9782914,
  coordinate_source = 'osm-nominatim:relation:2297418',
  coordinates_verified_at = NULL
WHERE id = 'area_kr_seoul';

UPDATE administrative_areas SET
  latitude = 33.9196418, longitude = 134.2509634,
  coordinate_source = 'osm-nominatim:relation:3795000',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_36';

UPDATE administrative_areas SET
  latitude = 34.7339685, longitude = 136.5154489,
  coordinate_source = 'osm-nominatim:relation:812190',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_24';

UPDATE administrative_areas SET
  latitude = 38.4746705, longitude = 140.083237,
  coordinate_source = 'osm-nominatim:relation:3790869',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_06';

UPDATE administrative_areas SET
  latitude = 31.2312707, longitude = 121.4700152,
  coordinate_source = 'osm-nominatim:relation:913067',
  coordinates_verified_at = NULL
WHERE id = 'area_cn_shanghai';

UPDATE administrative_areas SET
  latitude = 39.9057136, longitude = 116.3912972,
  coordinate_source = 'osm-nominatim:relation:912940',
  coordinates_verified_at = NULL
WHERE id = 'area_cn_beijing';

UPDATE administrative_areas SET
  latitude = 23.1288429, longitude = 113.2589581,
  coordinate_source = 'osm-nominatim:relation:3287346',
  coordinates_verified_at = NULL
WHERE id = 'area_cn_guangzhou';

UPDATE administrative_areas SET
  latitude = 35.6937632, longitude = 139.7036319,
  coordinate_source = 'osm-nominatim:relation:1758858',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_13104';

UPDATE administrative_areas SET
  latitude = 36.9890574, longitude = 136.8162839,
  coordinate_source = 'osm-nominatim:relation:3794726',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_17';

UPDATE administrative_areas SET
  latitude = 33.6013646, longitude = 132.8185275,
  coordinate_source = 'osm-nominatim:relation:3795063',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_38';

UPDATE administrative_areas SET
  latitude = 34.9418212, longitude = 132.537439,
  coordinate_source = 'osm-nominatim:relation:3346137',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_32';

UPDATE administrative_areas SET
  latitude = 26.5707754, longitude = 128.0255901,
  coordinate_source = 'osm-nominatim:relation:3795635',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_47';

UPDATE administrative_areas SET
  latitude = 36.2869536, longitude = 140.4703384,
  coordinate_source = 'osm-nominatim:relation:2682940',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_08';

UPDATE administrative_areas SET
  latitude = 35.6399328, longitude = 138.6380495,
  coordinate_source = 'osm-nominatim:relation:3578391',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_19';

UPDATE administrative_areas SET
  latitude = 39.5713763, longitude = 141.4253574,
  coordinate_source = 'osm-nominatim:relation:3792412',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_03';

UPDATE administrative_areas SET
  latitude = 35.3555075, longitude = 133.8678525,
  coordinate_source = 'osm-nominatim:relation:3285636',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_31';

UPDATE administrative_areas SET
  latitude = 36.52198, longitude = 139.033483,
  coordinate_source = 'osm-nominatim:relation:1851649',
  coordinates_verified_at = NULL
WHERE id = 'area_jp_10';

UPDATE venues SET
  latitude = 35.8951196, longitude = 139.630753,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:23876795',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_02f495bdfb2e984e7a5a0574';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_02f495bdfb2e984e7a5a0574', 'osm', '23876795', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_02f495bdfb2e984e7a5a0574');

UPDATE venues SET
  latitude = 35.5122725, longitude = 139.6201921,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:123630243',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_1802db716040b0ab505f15f5';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_1802db716040b0ab505f15f5', 'osm', '123630243', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_1802db716040b0ab505f15f5');

UPDATE venues SET
  latitude = 35.6933554, longitude = 139.7498704,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:43896730',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_9ee5200888ebff6f0955ed78';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_9ee5200888ebff6f0955ed78', 'osm', '43896730', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_9ee5200888ebff6f0955ed78');

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:relation:16117426',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_689ddf1faa751e38ed9d7ed5';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_689ddf1faa751e38ed9d7ed5', 'osm', '16117426', 'relation', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_689ddf1faa751e38ed9d7ed5');

UPDATE venues SET
  latitude = 34.678546, longitude = 135.4952992,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:5418175321',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_ae578700f2e3581292782b55';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_ae578700f2e3581292782b55', 'osm', '5418175321', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_ae578700f2e3581292782b55');

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_743c86e2a963c0fee1922516';

UPDATE venues SET
  latitude = 35.6325938, longitude = 139.8891977,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:152465277',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_6ffe7f005b731fb7256381b5';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_6ffe7f005b731fb7256381b5', 'osm', '152465277', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_6ffe7f005b731fb7256381b5');

UPDATE venues SET
  latitude = 1.2935198, longitude = 103.8572572,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:393090489',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_59f7d90deb03c839b7fc1a96';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_59f7d90deb03c839b7fc1a96', 'osm', '393090489', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_59f7d90deb03c839b7fc1a96');

UPDATE venues SET
  latitude = 35.7048566, longitude = 139.4118845,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:13759899060',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_9aba9672867d8ce261bf66dc';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_9aba9672867d8ce261bf66dc', 'osm', '13759899060', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_9aba9672867d8ce261bf66dc');

UPDATE venues SET
  latitude = 35.5473262, longitude = 139.7566254,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:8349128479',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_2f2d33c977442b4a9ecf3051';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_2f2d33c977442b4a9ecf3051', 'osm', '8349128479', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_2f2d33c977442b4a9ecf3051');

UPDATE venues SET
  latitude = 35.6955754, longitude = 139.7007704,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:11045809946',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_8ee67f70bc37751b8e901767';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_8ee67f70bc37751b8e901767', 'osm', '11045809946', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_8ee67f70bc37751b8e901767');

UPDATE venues SET
  latitude = 34.6684698, longitude = 135.4958072,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:1739916839',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_a34e3c9bd1040b9da0fe16ba';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_a34e3c9bd1040b9da0fe16ba', 'osm', '1739916839', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_a34e3c9bd1040b9da0fe16ba');

UPDATE venues SET
  latitude = 34.6605127, longitude = 135.5046982,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_legacy_4bb0b847c3e5c52b7be08a3f',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_official_475af87fdc42267ce791f1c';

UPDATE venues SET
  latitude = 34.6893887, longitude = 135.4862728,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_eda32029ca3754541445d813',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_0a2306ef2bba1c3a14f9d145';

UPDATE venues SET
  latitude = 34.6639818, longitude = 135.2101427,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:182322091',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_772e73ba472a510c712f7333';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_772e73ba472a510c712f7333', 'osm', '182322091', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_772e73ba472a510c712f7333');

UPDATE venues SET
  latitude = 35.1695094, longitude = 136.9205008,
  coordinate_precision = 'building',
  coordinate_source = 'derived-venue:ven_mig_phase2_26dbb7495083bef3d61136bd',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_03e4176fe85d009eac66159f';

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_1f725a57b9c4ad42fa036c04';

UPDATE venues SET
  latitude = 35.6297628, longitude = 139.7939817,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:1882511338',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_d1f05335cff2076621ab9cf2';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_d1f05335cff2076621ab9cf2', 'osm', '1882511338', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_d1f05335cff2076621ab9cf2');

UPDATE venues SET
  latitude = 35.168073, longitude = 136.8792186,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_legacy_930a86f07545fbaf940309d5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_official_34acbfe784e535a2fc7247b';

UPDATE venues SET
  latitude = 31.5907264, longitude = 130.5518047,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:117360720',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_e766c8751ee9a858619048cb';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_e766c8751ee9a858619048cb', 'osm', '117360720', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_e766c8751ee9a858619048cb');

UPDATE venues SET
  latitude = 37.399133, longitude = 140.3863864,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:3530949682',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_63e1cec6b4c8d3e6bb3ec4fb';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_63e1cec6b4c8d3e6bb3ec4fb', 'osm', '3530949682', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_63e1cec6b4c8d3e6bb3ec4fb');

UPDATE venues SET
  latitude = 35.5278068, longitude = 139.6972738,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:158883031',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_37fbcc2da4e052d41726d39f';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_37fbcc2da4e052d41726d39f', 'osm', '158883031', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_37fbcc2da4e052d41726d39f');

UPDATE venues SET
  latitude = 35.5278068, longitude = 139.6972738,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:158883031',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_08e4c4b40f19b95df4441caf';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_08e4c4b40f19b95df4441caf', 'osm', '158883031', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_08e4c4b40f19b95df4441caf');

UPDATE venues SET
  latitude = 34.2337535, longitude = 135.1745984,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:475064365',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_00d8a1cad5af2bdb6ba36b5f';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_00d8a1cad5af2bdb6ba36b5f', 'osm', '475064365', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_00d8a1cad5af2bdb6ba36b5f');

UPDATE venues SET
  latitude = 33.2330363, longitude = 131.6110327,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:857562286',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_2d1c33d30f2421c10851da63';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_2d1c33d30f2421c10851da63', 'osm', '857562286', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_2d1c33d30f2421c10851da63');

UPDATE venues SET
  latitude = 35.1695094, longitude = 136.9205008,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:4569988844',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_26dbb7495083bef3d61136bd';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_26dbb7495083bef3d61136bd', 'osm', '4569988844', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_26dbb7495083bef3d61136bd');

UPDATE venues SET
  latitude = 34.7589851, longitude = 135.495631,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:6311734785',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_f7f0681d4fe35067494160ed';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_f7f0681d4fe35067494160ed', 'osm', '6311734785', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_f7f0681d4fe35067494160ed');

UPDATE venues SET
  latitude = 34.6685114, longitude = 135.4960182,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:9645205170',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_8ab340bbdc7d3770782718b2';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_8ab340bbdc7d3770782718b2', 'osm', '9645205170', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_8ab340bbdc7d3770782718b2');

UPDATE venues SET
  latitude = -6.1457858, longitude = 106.8462134,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:34327586',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_7089526ad9231f204e3e0fb6';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_7089526ad9231f204e3e0fb6', 'osm', '34327586', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_7089526ad9231f204e3e0fb6');

UPDATE venues SET
  latitude = 35.4597025, longitude = 139.625957,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:827816737',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_763d01910e0d22930aa8e422';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_763d01910e0d22930aa8e422', 'osm', '827816737', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_763d01910e0d22930aa8e422');

UPDATE venues SET
  latitude = 36.6986328, longitude = 137.212086,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:2057319197',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_016ffa8f2141a68a5b9889e2';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_016ffa8f2141a68a5b9889e2', 'osm', '2057319197', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_016ffa8f2141a68a5b9889e2');

UPDATE venues SET
  latitude = 34.708497, longitude = 135.4998413,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:12987473714',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_6528f61c65f2a045434b04f5';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_6528f61c65f2a045434b04f5', 'osm', '12987473714', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_6528f61c65f2a045434b04f5');

UPDATE venues SET
  latitude = 36.6445585, longitude = 138.1897829,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:10107392495',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_98320a0ac3bf1333ff759bdf';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_98320a0ac3bf1333ff759bdf', 'osm', '10107392495', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_98320a0ac3bf1333ff759bdf');

UPDATE venues SET
  latitude = 34.6893774, longitude = 135.8343127,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:206347043',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_ef96ae309b6a06c152b64717';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_ef96ae309b6a06c152b64717', 'osm', '206347043', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_ef96ae309b6a06c152b64717');

UPDATE venues SET
  latitude = 35.6665157, longitude = 139.6970031,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:102123743',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_f06998efc519158ada049747';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_f06998efc519158ada049747', 'osm', '102123743', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_f06998efc519158ada049747');

UPDATE venues SET
  latitude = 34.3967472, longitude = 132.4568769,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:13078116750',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_925be32775b5c0674fef738e';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_925be32775b5c0674fef738e', 'osm', '13078116750', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_925be32775b5c0674fef738e');

UPDATE venues SET
  latitude = 34.393144, longitude = 132.4653095,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:13674776134',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_496a174ecef34bfcc40eed53';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_496a174ecef34bfcc40eed53', 'osm', '13674776134', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_496a174ecef34bfcc40eed53');

UPDATE venues SET
  latitude = 35.7033222, longitude = 139.7545794,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:5340434078',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_5e49508761e084f18c72990f';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_5e49508761e084f18c72990f', 'osm', '5340434078', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_5e49508761e084f18c72990f');

UPDATE venues SET
  latitude = 34.9788156, longitude = 135.8998357,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:1234090329',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_1f4e2174d9df9381d802d1b1';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_1f4e2174d9df9381d802d1b1', 'osm', '1234090329', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_1f4e2174d9df9381d802d1b1');

UPDATE venues SET
  latitude = 43.0493451, longitude = 141.3531647,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:5603040046',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_ce33e2ea39dfae411e5841f8';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_ce33e2ea39dfae411e5841f8', 'osm', '5603040046', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_ce33e2ea39dfae411e5841f8');

UPDATE venues SET
  latitude = 35.455818, longitude = 139.6283661,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:543069456',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_e35928b68231520768d0b654';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_e35928b68231520768d0b654', 'osm', '543069456', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_e35928b68231520768d0b654');

UPDATE venues SET
  latitude = 34.6605127, longitude = 135.5046982,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:4957598469',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_4bb0b847c3e5c52b7be08a3f';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_4bb0b847c3e5c52b7be08a3f', 'osm', '4957598469', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_4bb0b847c3e5c52b7be08a3f');

UPDATE venues SET
  latitude = 34.6605127, longitude = 135.5046982,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_legacy_4bb0b847c3e5c52b7be08a3f',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_b204fe8b1db2256811af10de';

UPDATE venues SET
  latitude = 34.6893887, longitude = 135.4862728,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:179071378',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_eda32029ca3754541445d813';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_eda32029ca3754541445d813', 'osm', '179071378', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_eda32029ca3754541445d813');

UPDATE venues SET
  latitude = 35.307271, longitude = 136.8187109,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:671183643',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_official_93945bd340280da9ba01c89';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_official_93945bd340280da9ba01c89', 'osm', '671183643', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_official_93945bd340280da9ba01c89');

UPDATE venues SET
  latitude = 35.307271, longitude = 136.8187109,
  coordinate_precision = 'building',
  coordinate_source = 'derived-venue:ven_mig_official_93945bd340280da9ba01c89',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_c23c45319223048ae0611007';

UPDATE venues SET
  latitude = 34.4125248, longitude = 132.4625908,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:106216062',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_6cce00fa95477a032fe351b9';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_6cce00fa95477a032fe351b9', 'osm', '106216062', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_6cce00fa95477a032fe351b9');

UPDATE venues SET
  latitude = 34.595613, longitude = 133.7762932,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:4420437825',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_d6d604fb6e9f7f605e0e2a47';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_d6d604fb6e9f7f605e0e2a47', 'osm', '4420437825', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_d6d604fb6e9f7f605e0e2a47');

UPDATE venues SET
  latitude = 35.6596537, longitude = 139.7300686,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:13647004152',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_7a9644b00601ac338bc10e2d';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_7a9644b00601ac338bc10e2d', 'osm', '13647004152', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_7a9644b00601ac338bc10e2d');

UPDATE venues SET
  latitude = 39.939462, longitude = 116.3379073,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:72725678',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_61d20697376e3fd65950a824';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_61d20697376e3fd65950a824', 'osm', '72725678', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_61d20697376e3fd65950a824');

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_a5a2924b423a1ec334494e7e';

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_602a6981aed456ffad14c2c4';

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_32a6eca9bd23f3c441ccd66e';

UPDATE venues SET
  latitude = 35.6473019, longitude = 140.0346524,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_689ddf1faa751e38ed9d7ed5',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_8c394e5d751d2f52e56a9f73';

UPDATE venues SET
  latitude = 35.0160683, longitude = 135.7828961,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:619903245',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_61d35adfa7d14534cd178b2c';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_61d35adfa7d14534cd178b2c', 'osm', '619903245', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_61d35adfa7d14534cd178b2c');

UPDATE venues SET
  latitude = 35.6569448, longitude = 139.7571847,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:111603914',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_40fb772f37ff86cf7d5e5000';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_40fb772f37ff86cf7d5e5000', 'osm', '111603914', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_40fb772f37ff86cf7d5e5000');

UPDATE venues SET
  latitude = 36.5584681, longitude = 136.6652329,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:304613928',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_b0d6c010ff2df5fc9de3127e';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_b0d6c010ff2df5fc9de3127e', 'osm', '304613928', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_b0d6c010ff2df5fc9de3127e');

UPDATE venues SET
  latitude = 35.6297628, longitude = 139.7939817,
  coordinate_precision = 'site',
  coordinate_source = 'derived-venue:ven_mig_phase2_d1f05335cff2076621ab9cf2',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_a8545fae76dd418d6f7cef76';

UPDATE venues SET
  latitude = 26.2154389, longitude = 127.6903573,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:node:4839547221',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_d7536b3cb05074bdb8d435eb';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_d7536b3cb05074bdb8d435eb', 'osm', '4839547221', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_d7536b3cb05074bdb8d435eb');

UPDATE venues SET
  latitude = 33.6039554, longitude = 130.4020808,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:node:10736292678',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_af0c9091dda3adf78d2b18ee';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_af0c9091dda3adf78d2b18ee', 'osm', '10736292678', 'node', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_af0c9091dda3adf78d2b18ee');

UPDATE venues SET
  latitude = 35.168073, longitude = 136.8792186,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:way:199957333',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_930a86f07545fbaf940309d5';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_930a86f07545fbaf940309d5', 'osm', '199957333', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_930a86f07545fbaf940309d5');

UPDATE venues SET
  latitude = 35.6670276, longitude = 139.7460078,
  coordinate_precision = 'site',
  coordinate_source = 'osm-nominatim:relation:18181013',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_phase2_7a288b6ae8fb387da69b50b4';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_phase2_7a288b6ae8fb387da69b50b4', 'osm', '18181013', 'relation', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_phase2_7a288b6ae8fb387da69b50b4');

UPDATE venues SET
  latitude = 36.5588717, longitude = 136.6585031,
  coordinate_precision = 'building',
  coordinate_source = 'osm-nominatim:way:300752558',
  coordinates_verified_at = NULL, updated_at = '2026-08-23T17:50:44.407Z'
WHERE id = 'ven_mig_legacy_312268578f970c37b90b76ce';

INSERT OR IGNORE INTO venue_external_ids
  (venue_id, provider, external_id, external_type, checked_at)
SELECT 'ven_mig_legacy_312268578f970c37b90b76ce', 'osm', '300752558', 'way', '2026-08-23T17:50:44.407Z'
WHERE EXISTS (SELECT 1 FROM venues WHERE id = 'ven_mig_legacy_312268578f970c37b90b76ce');
