/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=WebWorkerBindings apps/web/src/worker-bindings.d.ts` (hash: b5a7a5649fa4e691ebf5b49e80698445)
interface __BaseEnv_WebWorkerBindings {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: string;
	MAP_TILE_URL: string;
	ACCESS_TEAM_DOMAIN?: string;
	ACCESS_AUD?: string;
	APP_ENV?: string;
	ADMIN_PUBLISHERS?: string;
	DEV_AUTH_BYPASS?: string;
}
declare namespace Cloudflare {
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		SITE_URL: string;
		MAP_TILE_URL: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
	}
	interface StagingEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		SITE_URL: string;
		MAP_TILE_URL: string;
		APP_ENV: string;
		ACCESS_TEAM_DOMAIN: string;
		ADMIN_PUBLISHERS: string;
		DEV_AUTH_BYPASS: string;
		ACCESS_AUD: string;
	}
	interface Env extends __BaseEnv_WebWorkerBindings {}
}
interface WebWorkerBindings extends __BaseEnv_WebWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "MAP_TILE_URL" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "APP_ENV" | "ADMIN_PUBLISHERS" | "DEV_AUTH_BYPASS">> {}
}
